### ISSUE TITLE
setup_irods.py hangs when environment file provided

### ISSUE THREAD

**Issue by bnordgren** [mjstealey/irods-provider-postgres#2]
When an `--env-file` is provided (as in Example 2), the setup_irods.py script eats 100% of the CPU and never completes. This is true even when the `--env-file` contains the exact same values specified by the `ENV` directives in the dockerfile. It also occurs when using the environment file provided in Example 2.

**Comment by mjstealey** [comment]
@bnordgren - new PR merged for 4.2.2 that should address this.
Ref: PR #4

**Comment by mjstealey** [comment]
Issue has been [resolved](https://github.com/mjstealey/irods-provider-postgres/issues/7#issuecomment-344335170), closing
