### ISSUE TITLE
restarting an irods container fails

### ISSUE THREAD

**Issue by bnordgren** [mjstealey/irods-provider-postgres#3]
Attempting to start a container with pre-existing configuration/database/"vault" fails within 20 seconds of the run command with no obvious cause. Two separate test cases have the same result:

- A container with no volumes mounted, but which has been stopped and restarted.
- A new container which has volumes mounted as in Example 3, where the volumes possess configuration and database files from a previous setup. 

In essence, this feature interferes with trying to persist data through a stop-start cycle.

**Comment by mjstealey** [comment]
@bnordgren - new PR merged for 4.2.2 that should address this.
Ref: PR https://github.com/mjstealey/irods-provider-postgres/pull/4

**Comment by bnordgren** [comment]
@browe-fs Check out PR #4

**Comment by mjstealey** [comment]
@bnordgren, @browe-fs, @trel - Updated use case example to be relevant to an actual deploy.
https://github.com/mjstealey/irods-provider-postgres#real_usage

**Comment by mjstealey** [comment]
Issue has been [resolved](https://github.com/mjstealey/irods-provider-postgres/issues/7#issuecomment-344335170), closing
